export const cities = [
  {
    id: 1,
    name: 'Paris',
    image: require('./assets/paris.jpg'),
  },
  {
    id: 2,
    name: 'New York',
    image: require('./assets/newyork.jpg'),
  },
  {
    id: 3,
    name: 'Tokyo',
    image: require('./assets/tokyo.jpg'),
  },
  {
    id: 4,
    name: 'Venice',
    image: require('./assets/venice.jpg'),
  },
  {
    id: 5,
    name: 'Bali',
    image: require('./assets/bali.webp'),
  },
];

export const hotels = [
  {
    id: 1,
    cityId: 1,
    name: 'Hotel de Crillon',
    image: require('./assets/hotel_de_crillon.jpg'),
    details: 'A historic luxury hotel in Paris.',
    location: '10 Place de la Concorde, 75008 Paris, France',
    price: 1500,
  },
  {
    id: 2,
    cityId: 1,
    name: 'The Ritz Paris',
    image: require('./assets/ritz_paris.jpg'),
    details: 'A grand hotel in the heart of Paris.',
    location: '15 Place Vendôme, 75001 Paris, France',
    price: 2000,
  },
  {
    id: 3,
    cityId: 2,
    name: 'The Plaza',
    image: require('./assets/the_plaza.jpg'),
    details: 'A landmark hotel in New York City.',
    location: 'Fifth Avenue at Central Park South, New York, NY 10019, United States',
    price: 1800,
  },
  {
    id: 4,
    cityId: 2,
    name: 'The St. Regis New York',
    image: require('./assets/st_regis_new_york.jpg'),
    details: 'A historic luxury hotel in Midtown Manhattan.',
    location: 'Two E 55th St, New York, NY 10022, United States',
    price: 2200,
  },
  {
    id: 5,
    cityId: 3,
    name: 'Park Hyatt Tokyo',
    image: require('./assets/park_hyatt_tokyo.jpg'),
    details: 'An elegant hotel offering panoramic city views.',
    location: '3-7-1-2 Nishi-Shinjuku, Shinjuku-ku, Tokyo, 163-1055, Japan',
    price: 1200,
  },
  {
    id: 6,
    cityId: 3,
    name: 'Mandarin Oriental, Tokyo',
    image: require('./assets/mandarin_oriental_tokyo.jpg'),
    details: 'A luxury hotel with a Michelin-starred restaurant.',
    location: '2-1-1 Nihonbashi Muromachi, Chuo-ku, Tokyo, 103-8328, Japan',
    price: 1600,
  },
  {
    id: 7,
    cityId: 4,
    name: 'The Gritti Palace',
    image: require('./assets/gritti_palace.jpg'),
    details: 'A historic hotel on the Grand Canal.',
    location: 'Campo Santa Maria del Giglio, 2467, 30124 Venezia VE, Italy',
    price: 1700,
  },
  {
    id: 8,
    cityId: 4,
    name: 'Hotel Danieli',
    image: require('./assets/hotel_danieli.jpg'),
    details: 'A legendary hotel in a former palace.',
    location: 'Riva degli Schiavoni, 4196, 30122 Venezia VE, Italy',
    price: 1900,
  },
  {
    id: 9,
    cityId: 5,
    name: 'Four Seasons Resort Bali at Sayan',
    image: require('./assets/four_seasons_bali.jpg'),
    details: 'A luxurious resort in the Ayung River valley.',
    location: 'Jl. Raya Sayan, Sayan, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571, Indonesia',
    price: 1300,
  },
  {
    id: 10,
    cityId: 5,
    name: 'Mulia Resort & Villas Nusa Dua',
    image: require('./assets/mulia_resort_bali.jpg'),
    details: 'A beachfront resort with a stunning pool.',
    location: 'Jl. Raya Nusa Dua Selatan, Kawasan Sawangan, Nusa Dua, Benoa, Kec. Kuta Sel., Kabupaten Badung, Bali 80363, Indonesia',
    price: 1100,
  },
];

export const cars = [
  {
    id: 1,
    cityId: 1,
    name: 'Peugeot 208',
    image: require('./assets/peugeot_208.jpg'),
    details: 'A stylish and compact car, perfect for navigating the streets of Paris.',
    location: 'Charles de Gaulle Airport',
    price: 50,
  },
  {
    id: 2,
    cityId: 1,
    name: 'Renault Clio',
    image: require('./assets/renault_clio.jpg'),
    details: 'A popular and reliable hatchback.',
    location: 'Orly Airport',
    price: 45,
  },
  {
    id: 3,
    cityId: 2,
    name: 'Ford Mustang',
    image: require('./assets/ford_mustang.jpg'),
    details: 'An iconic American muscle car.',
    location: 'JFK Airport',
    price: 120,
  },
  {
    id: 4,
    cityId: 2,
    name: 'Chevrolet Camaro',
    image: require('./assets/chevrolet_camaro.jpg'),
    details: 'A powerful and stylish sports car.',
    location: 'LaGuardia Airport',
    price: 110,
  },
  {
    id: 5,
    cityId: 3,
    name: 'Toyota Prius',
    image: require('./assets/toyota_prius.jpg'),
    details: 'A fuel-efficient and reliable hybrid car.',
    location: 'Narita International Airport',
    price: 60,
  },
  {
    id: 6,
    cityId: 3,
    name: 'Honda Fit',
    image: require('./assets/honda_fit.jpg'),
    details: 'A compact and practical car for city driving.',
    location: 'Haneda Airport',
    price: 55,
  },
  {
    id: 7,
    cityId: 4,
    name: 'Fiat 500',
    image: require('./assets/fiat_500.jpg'),
    details: 'A classic Italian city car.',
    location: 'Marco Polo Airport',
    price: 40,
  },
  {
    id: 8,
    cityId: 4,
    name: 'Alfa Romeo Giulietta',
    image: require('./assets/alfa_romeo_giulietta.jpg'),
    details: 'A stylish and sporty hatchback.',
    location: 'Treviso Airport',
    price: 65,
  },
  {
    id: 9,
    cityId: 5,
    name: 'Toyota Avanza',
    image: require('./assets/toyota_avanza.jpg'),
    details: 'A spacious and practical MPV for families.',
    location: 'Ngurah Rai International Airport',
    price: 35,
  },
  {
    id: 10,
    cityId: 5,
    name: 'Daihatsu Xenia',
    image: require('./assets/daihatsu_xenia.jpg'),
    details: 'A reliable and affordable MPV.',
    location: 'Ngurah Rai International Airport',
    price: 30,
  },
];
];
